/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.scholar.desktop.ui.grading;

import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import main.java.com.scholar.desktop.config.entities.SchoolData;
import main.java.com.scholar.desktop.engine.caller.api.v1.grading.response.GradingDetailResponse;
import main.java.com.scholar.desktop.engine.caller.api.v1.grading.response.GradingResponse;

/**
 *
 * @author mover
 */
public class GradingUI extends javax.swing.JPanel {

    /**
     * Creates new form GradingUI
     */
    private SchoolData schoolData;
    private static GradingUI instance;
    JTabbedPane jTabbedPane;

    public GradingUI(SchoolData schoolData) {
        this.schoolData = schoolData;
        jTabbedPane = new javax.swing.JTabbedPane();
        initComponents();
        jTabbedPane1.addChangeListener(changeListener);
    }

    public static GradingUI getInstance(SchoolData schoolData) {
        if (instance == null) {
            instance = new GradingUI(schoolData);
        }
        return instance;
    }

    ChangeListener changeListener = new ChangeListener() {
        @Override
        public void stateChanged(ChangeEvent changeEvent) {
            JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
            int index = sourceTabbedPane.getSelectedIndex();
            switch (index) {
                case 0:
                    ManageGradingUI.getInstance(schoolData).initData();
                    break;
                case 1:
                    AddGradingUI.getInstance(schoolData).initData();
                    break;
                case 2:
                    ManageGradingDetailUI.getInstance(schoolData).initData();
                    break;
                case 3:
                    AddGradingDetailUI.getInstance(schoolData).initData();
                    break;

                default:

                    break;
            }

        }
    };

    public void edit(GradingResponse gradingResponse) {

        jTabbedPane1.setSelectedIndex(1);
        // AddClassUI.getInstance(schoolData).initData();
        AddGradingUI.getInstance(schoolData).edit(gradingResponse);

    }
    
     public void edit(GradingDetailResponse gradingResponse) {

        jTabbedPane1.setSelectedIndex(3);
        // AddClassUI.getInstance(schoolData).initData();
        AddGradingDetailUI.getInstance(schoolData).edit(gradingResponse);

    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.add("Manage Grading", ManageGradingUI.getInstance(schoolData));
        jTabbedPane1.add("Add Grading", AddGradingUI.getInstance(schoolData));
        jTabbedPane1.add("Manage Grading Details ", ManageGradingDetailUI.getInstance(schoolData));
        jTabbedPane1.add("Add Grading Detail", AddGradingDetailUI.getInstance(schoolData));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
