/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.scholar.desktop.ui.administration.students.admission;

import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import main.java.com.scholar.desktop.config.entities.SchoolData;

/**
 *
 * @author Manny
 */
public class AdmissionsUI extends javax.swing.JPanel {

    /**
     * Creates new form AdmissionsUI
     */
    private static AdmissionsUI instance;
    private final SchoolData schoolData;

    public AdmissionsUI(SchoolData schoolData) {
        this.schoolData = schoolData;
        initComponents();
        jTabbedPane1.addChangeListener(changeListener);
        

    }

    /**
     *
     * @param schoolData
     * @return
     */
    public static AdmissionsUI getInstance(SchoolData schoolData) {
        if (instance == null) {
            instance = new AdmissionsUI(schoolData);
        }

        return instance;
    }

    ChangeListener changeListener = new ChangeListener() {
        @Override
        public void stateChanged(ChangeEvent changeEvent) {
            JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
            int index = sourceTabbedPane.getSelectedIndex();
            switch (index) {
                case 0:
                    ManageAdmissionsUI.getInstance(schoolData).initData();
                    break;
                case 1:
                    AddAdmissionsUI.getInstance(schoolData).initData();
                    break;
                default:
                   
                    break;
            }

        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.add("Manage Admissions", ManageAdmissionsUI.getInstance(schoolData));
        jTabbedPane1.add("Add Admission", AddAdmissionsUI.getInstance(schoolData));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
